config/routes.rb
Rails.application.routes.draw do
  resources :tipo_actividads

  resources :actividads

  resources :comentarios

  resources :nombre_transportes

  resources :transportes

  resources :tipo_lugars

  resources :imagens

  resources :ubicacions

  resources :ciudads

  resources :lugars

  root 'lugars#index'

end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  belongs_to :ciudad
  has_one :lugar
end

app/controllers/ubicacions_controller.rb
class UbicacionsController < ApplicationController
  before_action :set_ubicacion, only: [:show, :edit, :update, :destroy]

  # GET /ubicacions
  # GET /ubicacions.json
  def index
    @ubicacions = Ubicacion.all
  end

  # GET /ubicacions/1
  # GET /ubicacions/1.json
  def show
  end

  # GET /ubicacions/new
  def new
    @ubicacion = Ubicacion.new
  end

  # GET /ubicacions/1/edit
  def edit
  end

  # POST /ubicacions
  # POST /ubicacions.json
  def create
    @ubicacion = Ubicacion.new(ubicacion_params)

    respond_to do |format|
      if @ubicacion.save
        format.html { redirect_to @ubicacion, notice: 'Ubicacion se creó correctamente.' }
        format.json { render :show, status: :created, location: @ubicacion }
      else
        format.html { render :new }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ubicacions/1
  # PATCH/PUT /ubicacions/1.json
  def update
    respond_to do |format|
      if @ubicacion.update(ubicacion_params)
        format.html { redirect_to @ubicacion, notice: 'Ubicacion se actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @ubicacion }
      else
        format.html { render :edit }
        format.json { render json: @ubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ubicacions/1
  # DELETE /ubicacions/1.json
  def destroy
    @ubicacion.destroy
    respond_to do |format|
      format.html { redirect_to ubicacions_url, notice: 'Ubicacion se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ubicacion
      @ubicacion = Ubicacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ubicacion_params
      params.require(:ubicacion).permit(:longitud, :latitud, :referencia, :ciudad_id)
    end
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/views/ubicacions/_form.html.erb
<%= form_for @ubicacion, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :longitud, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :longitud, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitud, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :latitud, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :referencia, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :referencia, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ciudad, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select :ciudad, Ciudad.all, :id, :nombre_ciudad %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ubicacions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ubicacions/edit.html.erb
<%- model_class = Ubicacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => Ubicacion %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ubicacions/index.html.erb
<%- model_class = Ubicacion -%>

  <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic:400,100,600,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
<body>
<!-- header -->
  <div class="header">
    <div class="container">
      <!-- /logo -->
      <!-- top-nav -->
    <div class="top-nav">
      <span class="menu"> </span>
        <ul>
          <li><%= link_to 'Inicio', lugars_path %></li>
          <li><%= link_to 'Transportes', transportes_path %></li>
          <li class="active"><%= link_to 'Ubicaciones', ubicacions_path %></li>
          <li><%= link_to 'Galeria', imagens_path %></li>
          <li><%= link_to 'Tipo de lugares', tipo_lugars_path %></li>
          <li><%= link_to 'Actividades', actividads_path %></li>
            <div class="clearfix"> </div>
        </ul>
    </div>
    <!-- /top-nav -->
      <div class="clearfix"> </div>
    </div>
    <!-- /header -->
  </div>
  <!----- //End-banner---->
    <!----- /start-about---->
       <div id="projects" class="Project">
        <div class="project-section">
            <div class="about-head">
              <h3>Lugares</h3>
              <p><%= link_to 'Inicio', lugars_path %> / Lugares / Ubicaciones</p>
            </div>
        <div class="project-info">
         <div class="container">
            <div class="row">
                <div class="col-md-8 Project-works">
                   <div class="projects">
                      <div class="project_grid">
                      <% i= 0 %>
                      <% @ubicacions.each do |ubicacion| %>
                      <ul class="project_box">
                      <li class="mini-post-meta"><time datetime><span class="day"></span><span class="month">
                      <% i = i+1 %>
                      <%= i %>
                      </span></time></li>
                          <li class="desc"><h5><a href="#">
                          <a href="<%= lugar_path(ubicacion.lugar) %>" target="_blank"><%= ubicacion.lugar.nombre_lugar %></a>
                          </h5>
                          <br>Longitud: 
                          <%= ubicacion.longitud %>
                          <br>Latitud: 
                          <%= ubicacion.latitud %>
                          <br>Ciudad: 
                          <%= ubicacion.ciudad.nombre_ciudad %>
                          <br>Referencia: 
                          <%= ubicacion.referencia %>
                          </li>
                          <div class="clearfix"> </div>
                          <br><br>
                          <a href="<%= ubicacion_path(ubicacion) %>" class="btn btn-primary" id="boton_nuevo" target="_blank">Ver ubicación</a>
                        </ul>
                    <% end %>
                      </div>
                   </div>
                </div>
            </div>
                      <%= link_to t('.new', :default => t("Nueva ubicación")),
                    new_ubicacion_path,
                    :class => 'btn btn-primary', :id => 'boton_nuevo' %>
          </div>
          <div class="clearfix"> </div>


      </div>
    </div>
  </div>
        <div class="our-projects">  

       <div id="services" class="services">
        <div class="container">
            <div class="About-head">
              <h2>Informacion de lugares que deber&iacute;as visitar</h2>
            </div>
          <div class="service-grids">
              <div class="col-md-3 service-grid">
                 <%= image_tag "icono1.png", :alt => "Lugares", :title => "Lugares"%>
                <h3><%= link_to 'Lugares Turisticos', lugars_path %></h3>
              </div>
                <div class="col-md-3 service-grid">
                <%= image_tag "icono2.png", :alt => "Transportes", :title => "Transportes"%>
                <h3><%= link_to 'Transportes', transportes_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono3.png", :alt => "Galeria", :title => "Galeria"%>
                <h3><%= link_to 'Galeria', imagens_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono4.png", :alt => "Ubicaciones", :title => "Ubicaciones"%>
                <h3><%= link_to 'Ubicaciones', ubicacions_path %></h3>
              </div>
            <div class="clearfix"> </div>
          </div>
        </div>
       </div>
  <!----- //End-services---->
    <!----- /start-footer---->
        <div class="footer">
          <div class="container">
            <div class="copy-right">
              <p> 2015 <a href="http://twitter.com/ju4n5vc">LZG</a></p>
               <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br /><span class="final" xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Turismo Ecuador por</span> <span class="final" xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Juan Vivanco bajo licencia</span> <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons.</a>.
            </div>
            </div>                
          </div>
</body>

app/views/ubicacions/new.html.erb
<%- model_class = Ubicacion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nueva %{model}'], :model => Ubicacion %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ubicacions/show.html.erb
<%- model_class = Ubicacion -%>

<head>
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script>
                          function initialize() {
                            var i = 1;
                            var myLatlng = new google.maps.LatLng(<%= @ubicacion.latitud %>, <%= @ubicacion.longitud %>)
                            var mapProp = {
                              zoom:14,
                              center: myLatlng,
                              mapTypeId:google.maps.MapTypeId.ROADMAP
                            };
                            var map=new google.maps.Map(document.getElementById("Map"),mapProp);
                            var marker = new google.maps.Marker({
                                position: myLatlng,
                                map: map
                            });
                            i++;
                          }
                          google.maps.event.addDomListener(window, 'load', initialize);
                          </script>
</head>

<div class="page-header">
  <h1><%=t '.title', :default => Ubicacion %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:longitud) %></dt>
      <dd><pre class="prettyprint"><%= @ubicacion.longitud %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:latitud) %></dt>
      <dd><pre class="prettyprint"><%= @ubicacion.latitud %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:referencia) %></dt>
      <dd><pre class="prettyprint"><%= @ubicacion.referencia %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ciudad_id) %></dt>
      <dd><pre class="prettyprint"><%= @ubicacion.ciudad.nombre_ciudad %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nombre_lugar) %>
      </dt>
      <dd><pre class="prettyprint"><%= @ubicacion.lugar.nombre_lugar %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mapa) %>
      </dt>
      <dd><pre class="prettyprint"><div id="Map" style="width:500px;height:380px;"></div></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ubicacion_creada) %>
      <dd><pre class="prettyprint"><%=l @ubicacion.created_at, format: :long %></pre></dd>
      </dt>
        
                          
  </dl>
</div>
<div class="form-group">
  <%= link_to t('.back', :default => t("Atrás")),
              ubicacions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("Editar")),
              edit_ubicacion_path(@ubicacion), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("Eliminar")),
              ubicacion_path(@ubicacion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>