config/routes.rb
Rails.application.routes.draw do
  resources :tipo_actividads

  resources :actividads

  resources :comentarios

  resources :nombre_transportes

  resources :transportes

  resources :tipo_lugars

  resources :imagens

  resources :ubicacions

  resources :ciudads

  resources :lugars

  root 'lugars#index'

end

app/models/tipo_lugar.rb
class TipoLugar < ActiveRecord::Base
  has_many :lugars
end

app/controllers/tipo_lugars_controller.rb
class TipoLugarsController < ApplicationController
  before_action :set_tipo_lugar, only: [:show, :edit, :update, :destroy]

  # GET /tipo_lugars
  # GET /tipo_lugars.json
  def index
    @tipo_lugars = TipoLugar.all
  end

  # GET /tipo_lugars/1
  # GET /tipo_lugars/1.json
  def show
  end

  # GET /tipo_lugars/new
  def new
    @tipo_lugar = TipoLugar.new
  end

  # GET /tipo_lugars/1/edit
  def edit
  end

  # POST /tipo_lugars
  # POST /tipo_lugars.json
  def create
    @tipo_lugar = TipoLugar.new(tipo_lugar_params)

    respond_to do |format|
      if @tipo_lugar.save
        format.html { redirect_to @tipo_lugar, notice: 'Tipo lugar se creó correctamente.' }
        format.json { render :show, status: :created, location: @tipo_lugar }
      else
        format.html { render :new }
        format.json { render json: @tipo_lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_lugars/1
  # PATCH/PUT /tipo_lugars/1.json
  def update
    respond_to do |format|
      if @tipo_lugar.update(tipo_lugar_params)
        format.html { redirect_to @tipo_lugar, notice: 'Tipo lugar se actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @tipo_lugar }
      else
        format.html { render :edit }
        format.json { render json: @tipo_lugar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_lugars/1
  # DELETE /tipo_lugars/1.json
  def destroy
    @tipo_lugar.destroy
    respond_to do |format|
      format.html { redirect_to tipo_lugars_url, notice: 'Tipo lugar se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_lugar
      @tipo_lugar = TipoLugar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_lugar_params
      params.require(:tipo_lugar).permit(:nombre_tipo)
    end
end

app/helpers/tipo_lugars_helper.rb
module TipoLugarsHelper
end

app/views/tipo_lugars/_form.html.erb
<%= form_for @tipo_lugar, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nombre_tipo, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nombre_tipo, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  tipo_lugars_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/tipo_lugars/edit.html.erb
<%- model_class = TipoLugar -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => TipoLugar %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tipo_lugars/index.html.erb
<%- model_class = TipoLugar -%>
<!----- webfonts ------>
  <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic:400,100,600,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
<body>
<!-- header -->
  <div class="header">
    <div class="container">
      <!-- /logo -->
      <!-- top-nav -->
    <div class="top-nav">
      <span class="menu"> </span>
        <ul>
          <li><%= link_to 'Inicio', lugars_path %></li>
          <li><%= link_to 'Transportes', transportes_path %></li>
          <li><%= link_to 'Ubicaciones', ubicacions_path %></li>
          <li><%= link_to 'Galeria', imagens_path %></li>
          <li class="active"><%= link_to 'Tipo de lugares', tipo_lugars_path %></li>
          <li><%= link_to 'Actividades', actividads_path %></li>
            <div class="clearfix"> </div>
        </ul>
    </div>
    <!-- /top-nav -->
      <div class="clearfix"> </div>
    </div>
    <!-- /header -->
  </div>
  <!----- //End-banner---->
    <!----- /start-about---->
       <div id="projects" class="Project">
        <div class="project-section">
            <div class="about-head">
              <h3>Tipo Lugares</h3>
              <p><%= link_to 'Inicio', lugars_path %> / Tipo Lugares</p>
            </div>
        <div class="project-info">
         <div class="container">
            <div class="row">
                <div class="col-md-8 Project-works">
                   <div class="projects">
                      <div class="project_grid">
                      <% i= 0 %>
                      <% @tipo_lugars.each do |tipo_lugar| %>
                      <ul class="project_box">
                      <li class="mini-post-meta"><time datetime><span class="day"></span><span class="month">
                      <% i = i+1 %>
                      <%= i %>
                      </span></time></li>
                          <li class="desc"><h5><a href="#">
                          <%= link_to tipo_lugar.nombre_tipo, tipo_lugar_path(tipo_lugar) %>
                          </h5>
                          <iframe id='iframe' src='http://flickrit.com/slideshowholder.php?height=200&width=400&size=medium&tags=<%= tipo_lugar.nombre_tipo %>&thumbnails=0&transition=0&layoutType=fixed&sort=0' scrolling='no' frameborder='0' width='400px' height='200px'></iframe>
                          </li>
                          <div class="clearfix"> </div>

                        </ul>
                    <% end %>
                      </div>
                   </div>
                </div>
            </div>
                      <%= link_to t('.new', :default => t("Nuevo tipo lugar")),
                    new_tipo_lugar_path,
                    :class => 'btn btn-primary', :id => 'boton_nuevo' %>
          </div>
          <div class="clearfix"> </div>


      </div>
    </div>
  </div>
        <div class="our-projects">  

       <div id="services" class="services">
        <div class="container">
            <div class="About-head">
              <h2>Informacion de lugares que deber&iacute;as visitar</h2>
            </div>
          <div class="service-grids">
              <div class="col-md-3 service-grid">
                 <%= image_tag "icono1.png", :alt => "Lugares", :title => "Lugares"%>
                <h3><%= link_to 'Lugares Turisticos', lugars_path %></h3>
              </div>
                <div class="col-md-3 service-grid">
                <%= image_tag "icono2.png", :alt => "Transportes", :title => "Transportes"%>
                <h3><%= link_to 'Transportes', transportes_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono3.png", :alt => "Galeria", :title => "Galeria"%>
                <h3><%= link_to 'Galeria', imagens_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono4.png", :alt => "Ubicaciones", :title => "Ubicaciones"%>
                <h3><%= link_to 'Ubicaciones', ubicacions_path %></h3>
              </div>
            <div class="clearfix"> </div>
          </div>
        </div>
       </div>
  <!----- //End-services---->
    <!----- /start-footer---->
        <div class="footer">
          <div class="container">
            <div class="copy-right">
              <p> 2015 <a href="http://twitter.com/ju4n5vc">LZG</a></p>
               <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br /><span class="final" xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Turismo Ecuador por</span> <span class="final" xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Juan Vivanco bajo licencia</span> <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons.</a>.
            </div>
            </div>                
          </div>
</body>

app/views/tipo_lugars/new.html.erb
<%- model_class = TipoLugar -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nuevo %{model}'], :model => TipoLugar %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tipo_lugars/show.html.erb
<%- model_class = TipoLugar -%>
<div class="page-header">
  <h1><%=t '.title', :default => TipoLugar %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nombre_tipo) %></dt>
      <dd><pre class="prettyprint"><%= @tipo_lugar.nombre_tipo %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tipo_de_lugar_creado) %>
      <dd><pre class="prettyprint"><%=l @tipo_lugar.created_at, format: :long %></pre></dd>
      </dt>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("Atrás")),
              tipo_lugars_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("Editar")),
              edit_tipo_lugar_path(@tipo_lugar), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("Eliminar")),
              tipo_lugar_path(@tipo_lugar),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>