config/routes.rb
Rails.application.routes.draw do
  resources :tipo_actividads

  resources :actividads

  resources :comentarios

  resources :nombre_transportes

  resources :transportes

  resources :tipo_lugars

  resources :imagens

  resources :ubicacions

  resources :ciudads

  resources :lugars

  root 'lugars#index'

end

app/models/imagen.rb
class Imagen < ActiveRecord::Base
  belongs_to :lugar
  has_attached_file :foto, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :foto, :content_type => /\Aimage\/.*\Z/
end

app/controllers/imagens_controller.rb
class ImagensController < ApplicationController
  before_action :set_imagen, only: [:show, :edit, :update, :destroy]

  # GET /imagens
  # GET /imagens.json
  def index
    @imagens = Imagen.all
  end

  # GET /imagens/1
  # GET /imagens/1.json
  def show
  end

  # GET /imagens/new
  def new
    @imagen = Imagen.new
  end

  # GET /imagens/1/edit
  def edit
  end

  # POST /imagens
  # POST /imagens.json
  def create
    @imagen = Imagen.new(imagen_params)

    respond_to do |format|
      if @imagen.save
        format.html { redirect_to @imagen, notice: 'Imagen se creó correctamente.' }
        format.json { render :show, status: :created, location: @imagen }
      else
        format.html { render :new }
        format.json { render json: @imagen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imagens/1
  # PATCH/PUT /imagens/1.json
  def update
    respond_to do |format|
      if @imagen.update(imagen_params)
        format.html { redirect_to @imagen, notice: 'Imagen se actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @imagen }
      else
        format.html { render :edit }
        format.json { render json: @imagen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagens/1
  # DELETE /imagens/1.json
  def destroy
    @imagen.destroy
    respond_to do |format|
      format.html { redirect_to imagens_url, notice: 'Imagen se elimino correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagen
      @imagen = Imagen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagen_params
      params.require(:imagen).permit(:nombre_imagen, :imagen, :descripcion_imagen, :lugar_id, :foto)
    end
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/views/imagens/_form.html.erb
<%= form_for @imagen, :html => {:multipart => true, :class => 'form-horizontal form-model'} do |f| %> 
  <div class="form-group">
    <%= f.label :nombre_imagen, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nombre_imagen, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :Imagen, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.file_field :foto %>  
    </div>
  </div>
   <div class="form-group">
    <%= f.label :descripcion_imagen, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :descripcion_imagen, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lugar, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select :lugar, Lugar.all, :id, :nombre_lugar %>
    </div>
  </div>
  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ubicacions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>  

app/views/imagens/edit.html.erb
<%- model_class = Imagen -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editar %{model}'], :model => Imagen %></h1>
</div>
<%= render :partial => 'form' %>

app/views/imagens/index.html.erb
<%- model_class = Imagen -%>

<!----- webfonts ------>
  <link href='http://fonts.googleapis.com/css?family=Carrois+Gothic:400,100,600,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
<body>
<!-- header -->
  <div class="header">
    <div class="container">
      <!-- /logo -->
      <!-- top-nav -->
    <div class="top-nav">
      <span class="menu"> </span>
        <ul>
          <li><%= link_to 'Inicio', lugars_path %></li>
          <li><%= link_to 'Transportes', transportes_path %></li>
          <li><%= link_to 'Ubicaciones', ubicacions_path %></li>
          <li class="active"><%= link_to 'Galeria', imagens_path %></li>
          <li><%= link_to 'Tipo de lugares', tipo_lugars_path %></li>
          <li><%= link_to 'Actividades', actividads_path %></li>
            <div class="clearfix"> </div>
        </ul>
    </div>
    <!-- /top-nav -->
      <div class="clearfix"> </div>
    </div>
    <!-- /header -->
  </div>
  <!----- //End-banner---->
    <!----- /start-about---->
       <div id="projects" class="Project">
        <div class="project-section">
            <div class="about-head">
              <h3>Galeria</h3>
              <p><%= link_to 'Inicio', lugars_path %> / Lugares / Galeria</p>
            </div>
        <div class="project-info">
         <div class="container">
            <div class="row">
                <div class="col-md-8 Project-works">
                   <div class="projects">
                      <div class="project_grid">
                      <% i= 0 %>
                      <% @imagens.each do |imagen| %>
                      <ul class="project_box">
                      <li class="mini-post-meta"><time datetime><span class="day"></span><span class="month">
                      <% i = i+1 %>
                      <%= i %>
                      </span></time></li>
                          <li class="desc"><h5><a href="#">
                          <%= link_to imagen.nombre_imagen, imagen_path(imagen) %>
                          </h5>
                          <p><%= image_tag imagen.foto.url(:medium) %></p>
                          <br>Descripcción: 
                          <p><%= imagen.descripcion_imagen %></p>
                          <br>Lugar: <a href="<%= lugar_path(ubicacion.lugar) %>" target="_blank"><%= ubicacion.lugar.nombre_lugar %></a>
                          </li>
                          <div class="clearfix"> </div>
                        </ul>
                    <% end %>
                      </div>
                   </div>
                </div>
            </div>
                      <%= link_to t('.new', :default => t("Nueva imagen")),
                    new_imagen_path,
                    :class => 'btn btn-primary', :id => 'boton_nuevo' %>
          </div>
          <div class="clearfix"> </div>


      </div>
    </div>
  </div>
        <div class="our-projects">  

       <div id="services" class="services">
        <div class="container">
            <div class="About-head">
              <h2>Informacion de lugares que deber&iacute;as visitar</h2>
            </div>
          <div class="service-grids">
              <div class="col-md-3 service-grid">
                 <%= image_tag "icono1.png", :alt => "Lugares", :title => "Lugares"%>
                <h3><%= link_to 'Lugares Turisticos', lugars_path %></h3>
              </div>
                <div class="col-md-3 service-grid">
                <%= image_tag "icono2.png", :alt => "Transportes", :title => "Transportes"%>
                <h3><%= link_to 'Transportes', transportes_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono3.png", :alt => "Galeria", :title => "Galeria"%>
                <h3><%= link_to 'Galeria', imagens_path %></h3>
              </div>
              <div class="col-md-3 service-grid">
              <%= image_tag "icono4.png", :alt => "Ubicaciones", :title => "Ubicaciones"%>
                <h3><%= link_to 'Ubicaciones', ubicacions_path %></h3>
              </div>
            <div class="clearfix"> </div>
          </div>
        </div>
       </div>
  <!----- //End-services---->
    <!----- /start-footer---->
        <div class="footer">
          <div class="container">
            <div class="copy-right">
              <p> 2015 <a href="http://twitter.com/ju4n5vc">LZG</a></p>
               <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a><br /><span class="final" xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Turismo Ecuador por</span> <span class="final" xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Juan Vivanco bajo licencia</span> <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons.</a>.
            </div>
            </div>                
          </div>
</body>

app/views/imagens/new.html.erb
<%- model_class = Imagen -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nueva %{model}'], :model => Imagen %></h1>
</div>
<%= render :partial => 'form' %>

app/views/imagens/show.html.erb
<%- model_class = Imagen -%>
<div class="page-header">
  <h1><%=t '.title', :default => Imagen %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nombre_imagen) %></dt>
      <dd><pre class="prettyprint"><%= @imagen.nombre_imagen %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagen) %></dt>
      <dd><pre class="prettyprint"><%= image_tag @imagen.foto.url(:medium) %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descripcion_imagen) %></dt>
      <dd><pre class="prettyprint"><%= @imagen.descripcion_imagen %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:lugar_id) %></dt>
      <dd><pre class="prettyprint"><%= @imagen.lugar.nombre_lugar %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagen_creada) %>
      <dd><pre class="prettyprint"><%=l @imagen.created_at, format: :long %></pre></dd>
      </dt>
                          
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("Atrás")),
              imagens_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("Editar")),
              edit_imagen_path(@imagen), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("Eliminar")),
              imagen_path(@imagen),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>